// Auto-generated Russian Minecraft Item Names Dictionary
export const ruItemNames: Record<string, string> = {
  "air": "Воздух",
  "apple": "Яблоко",
  "arrow": "Стрела",
  "baked_potato": "Печёный картофель",
  "bamboo": "Бамбук",
  "barrel": "Бочка",
  "barrier": "Барьер",
  "basalt": "Базальт",
  "beacon": "Маяк",
  "bedrock": "Бедрок",
  "bee_nest": "Пчелиное гнездо",
  "beef": "Сырая говядина",
  "beehive": "Улей",
  "beetroot": "Свёкла",
  "beetroot_seeds": "Семена свёклы",
  "beetroot_soup": "Свекольный суп",
  "bell": "Колокол",
  "blaze_powder": "Огненный порошок",
  "blaze_rod": "Стержень ифрита",
  "bleeding": "Кровотечение",
  "blindness": "Слепота",
  "bone": "Кость",
  "bone_block": "Костяной блок",
  "bone_meal": "Костная мука",
  "book": "Книга",
  "bookshelf": "Книжная полка",
  "bow": "Лук",
  "bowl": "Миска",
  "bread": "Хлеб",
  "breeze_rod": "Стержень вихря",
  "brewing_stand": "Варочная стойка",
  "brick": "Кирпич",
  "bricks": "Кирпичи",
  "brush": "Кисть",
  "bucket": "Ведро",
  "bundle": "Мешок",
  "cactus": "Кактус",
  "cake": "Торт",
  "calcite": "Кальцит",
  "campfire": "Костёр",
  "candle": "Свеча",
  "carrot": "Морковь",
  "carrot_on_a_stick": "Удочка с морковью",
  "cartography_table": "Стол картографа",
  "carved_pumpkin": "Вырезанная тыква",
  "cauldron": "Котел",
  "chain": "Цепь",
  "charcoal": "Древесный уголь",
  "chest": "Сундук",
  "chest_minecart": "Вагонетка с сундуком",
  "chicken": "Сырая курятина",
  "chiseled_bookshelf": "Резная книжная полка",
  "chorus_flower": "Цветок хоруса",
  "chorus_fruit": "Плод хоруса",
  "chorus_plant": "Растение хоруса",
  "clay": "Глина",
  "clay_ball": "Комок глины",
  "clock": "Часы",
  "coal": "Уголь",
  "coal_block": "Угольный блок",
  "coal_ore": "Угольная руда",
  "cobblestone": "Булыжник",
  "cobweb": "Паутина",
  "cocoa_beans": "Какао-бобы",
  "cod": "Сырая треска",
  "cod_bucket": "Ведро с треской",
  "command_block": "Командный блок",
  "comparator": "Редстоуновый компаратор",
  "compass": "Компас",
  "composter": "Компостер",
  "conduit": "Морской источник",
  "cooked_beef": "Жареная говядина",
  "cooked_chicken": "Жареная курятина",
  "cooked_cod": "Жареная треска",
  "cooked_mutton": "Жареная баранина",
  "cooked_porkchop": "Жареная свинина",
  "cooked_rabbit": "Жареная крольчатина",
  "cooked_salmon": "Жареный лосось",
  "cookie": "Печенье",
  "copper_block": "Медный блок",
  "copper_bulb": "Медная лампа",
  "copper_door": "Медная дверь",
  "copper_grate": "Медная решётка",
  "copper_ingot": "Медный слиток",
  "copper_ore": "Медная руда",
  "copper_trapdoor": "Медный люк",
  "cornflower": "Василёк",
  "crafting_table": "Верстак",
  "creeper_head": "Голова крипера",
  "crossbow": "Арбалет",
  "crying_obsidian": "Плачущий обсидиан",
  "dandelion": "Одуванчик",
  "daylight_detector": "Детектор дневного света",
  "dead_bush": "Мёртвый куст",
  "debug_stick": "Отладочная палочка",
  "decorated_pot": "Украшенный глиняный кувшин",
  "deepslate": "Глубинный сланец",
  "detector_rail": "Рельсы с датчиком",
  "diamond": "Алмаз",
  "diamond_axe": "Алмазный топор",
  "diamond_block": "Алмазный блок",
  "diamond_boots": "Алмазные ботинки",
  "diamond_chestplate": "Алмазный нагрудник",
  "diamond_helmet": "Алмазный шлем",
  "diamond_hoe": "Алмазная мотыга",
  "diamond_horse_armor": "Алмазная конская броня",
  "diamond_leggings": "Алмазные поножи",
  "diamond_ore": "Алмазная руда",
  "diamond_pickaxe": "Алмазная кирка",
  "diamond_shovel": "Алмазная лопата",
  "diamond_sword": "Алмазный меч",
  "diorite": "Диорит",
  "dirt": "Земля",
  "coarse_dirt": "Каменистая земля",
  "rooted_dirt": "Укоренённая земля",
  "dirt_path": "Тропинка",
  "dispenser": "Раздатчик",
  "dragon_breath": "Драконье дыхание",
  "dragon_egg": "Яйцо дракона",
  "dragon_head": "Голова дракона",
  "dried_kelp": "Сушёная ламинария",
  "dried_kelp_block": "Блок сушёной ламинарии",
  "dripstone_block": "Капельниковый блок",
  "dropper": "Выбрасыватель",
  "echo_shard": "Осколок эха",
  "egg": "Яйцо",
  "elytra": "Элитры",
  "emerald": "Изумруд",
  "emerald_block": "Изумрудный блок",
  "emerald_ore": "Изумрудная руда",
  "enchanted_book": "Чародейская книга",
  "enchanted_golden_apple": "Зачарованное золотое яблоко",
  "enchanting_table": "Чародейский стол",
  "end_crystal": "Кристалл Края",
  "end_portal_frame": "Рамка портала в Край",
  "end_rod": "Стержень Края",
  "end_stone": "Эндер-няк",
  "ender_chest": "Эндер-сундук",
  "ender_eye": "Око Края",
  "ender_pearl": "Жемчуг Края",
  "experience_bottle": "Пузырёк опыта",
  "farmland": "Пашня",
  "feather": "Перо",
  "fermented_spider_eye": "Маринованный паучий глаз",
  "fern": "Папоротник",
  "fire_charge": "Огненный шар",
  "firework_rocket": "Фейерверк",
  "firework_star": "Пиротехническая звезда",
  "fishing_rod": "Удочка",
  "fletching_table": "Стол лучника",
  "flint": "Кремень",
  "flint_and_steel": "Огниво",
  "flower_pot": "Цветочный горшок",
  "furnace": "Печь",
  "furnace_minecart": "Вагонетка с печью",
  "ghast_tear": "Слеза гаста",
  "gilded_blackstone": "Позолоченный чернокамень",
  "glass": "Стекло",
  "glass_bottle": "Пузырёк",
  "glass_pane": "Стеклянная панель",
  "glistering_melon_slice": "Сверкающий ломтик арбуза",
  "glow_berries": "Светящиеся ягоды",
  "glow_ink_sac": "Светящийся чернильный мешок",
  "glow_item_frame": "Светящаяся рамка",
  "glowing": "Свечение",
  "glowstone": "Светокамень",
  "glowstone_dust": "Светопыль",
  "goat_horn": "Козий рог",
  "gold_block": "Золотой блок",
  "gold_ingot": "Золотой слиток",
  "gold_nugget": "Золотой самородок",
  "gold_ore": "Золотая руда",
  "golden_apple": "Золотое яблоко",
  "golden_axe": "Золотой топор",
  "golden_boots": "Золотые ботинки",
  "golden_carrot": "Золотая морковь",
  "golden_chestplate": "Золотой нагрудник",
  "golden_helmet": "Золотой шлем",
  "golden_hoe": "Золотая мотыга",
  "golden_horse_armor": "Золотая конская броня",
  "golden_leggings": "Золотые поножи",
  "golden_pickaxe": "Золотая кирка",
  "golden_shovel": "Золотая лопата",
  "golden_sword": "Золотой меч",
  "granite": "Гранит",
  "grass": "Трава",
  "grass_block": "Блок травы",
  "gravel": "Гравий",
  "grindstone": "Точило",
  "gunpowder": "Порох",
  "hanging_roots": "Свисающие корни",
  "hay_block": "Сноп сена",
  "heart_of_the_sea": "Сердце моря",
  "heavy_core": "Тяжёлое ядро",
  "honey_block": "Блок мёда",
  "honey_bottle": "Бутылочка мёда",
  "honeycomb": "Пчелиные соты",
  "honeycomb_block": "Блок пчелиных сот",
  "hopper": "Воронка",
  "hopper_minecart": "Вагонетка с воронкой",
  "ice": "Лёд",
  "ink_sac": "Чернильный мешок",
  "iron_axe": "Железный топор",
  "iron_bars": "Железная решётка",
  "iron_block": "Железный блок",
  "iron_boots": "Железные ботинки",
  "iron_chestplate": "Железный нагрудник",
  "iron_door": "Железная дверь",
  "iron_helmet": "Железный шлем",
  "iron_hoe": "Железная мотыга",
  "iron_horse_armor": "Железная конская броня",
  "iron_ingot": "Железный слиток",
  "iron_leggings": "Железные поножи",
  "iron_nugget": "Железный самородок",
  "iron_ore": "Железная руда",
  "iron_pickaxe": "Железная кирка",
  "iron_shovel": "Железная лопата",
  "iron_sword": "Железный меч",
  "iron_trapdoor": "Железный люк",
  "item_frame": "Рамка",
  "jack_o_lantern": "Светильник Джека",
  "jukebox": "Проигрыватель",
  "kelp": "Ламинария",
  "ladder": "Лестница",
  "lantern": "Фонарь",
  "lapis_block": "Лазуритовый блок",
  "lapis_lazuli": "Лазурит",
  "lapis_ore": "Лазуритовая руда",
  "lead": "Повод",
  "leather": "Кожа",
  "leather_boots": "Кожаные ботинки",
  "leather_chestplate": "Кожаная куртка",
  "leather_helmet": "Кожаный шлем",
  "leather_horse_armor": "Кожаная конская броня",
  "leather_leggings": "Кожаные штаны",
  "lectern": "Кафедра",
  "lever": "Рычаг",
  "light": "Свет",
  "lightning_rod": "Громоотвод",
  "lily_pad": "Кувшинка",
  "lodestone": "Магнетит",
  "loom": "Ткацкий станок",
  "mace": "Булава",
  "magma_block": "Блок магмы",
  "magma_cream": "Сгусток магмы",
  "mangrove_roots": "Корни мангрового дерева",
  "map": "Карта",
  "melon": "Арбуз",
  "melon_seeds": "Семена арбуза",
  "melon_slice": "Ломтик арбуза",
  "milk_bucket": "Ведро молока",
  "minecart": "Вагонетка",
  "moss_block": "Блок мха",
  "moss_carpet": "Ковёр из мха",
  "mossy_cobblestone": "Замшелый булыжник",
  "mud": "Грязь",
  "mud_bricks": "Глиняные кирпичи",
  "mushroom_stem": "Ножка гриба",
  "mushroom_stew": "Тушёные грибы",
  "mutton": "Сырая баранина",
  "mycelium": "Мицелий",
  "name_tag": "Бирка",
  "nautilus_shell": "Раковина наутилуса",
  "nether_brick": "Незерский кирпич",
  "nether_bricks": "Незерские кирпичи",
  "nether_gold_ore": "Незерская золотая руда",
  "nether_quartz_ore": "Кварцевая руда",
  "nether_star": "Звезда Нижнего мира",
  "nether_wart": "Адский нарост",
  "nether_wart_block": "Блок адского нароста",
  "netherite_axe": "Незеритовый топор",
  "netherite_block": "Незеритовый блок",
  "netherite_boots": "Незеритовые ботинки",
  "netherite_chestplate": "Незеритовый нагрудник",
  "netherite_helmet": "Незеритовый шлем",
  "netherite_hoe": "Незеритовая мотыга",
  "netherite_ingot": "Незеритовый слиток",
  "netherite_leggings": "Незеритовые поножи",
  "netherite_pickaxe": "Незеритовая кирка",
  "netherite_scrap": "Незеритовый обломок",
  "netherite_shovel": "Незеритовая лопата",
  "netherite_sword": "Незеритовый меч",
  "netherrack": "Незерракт",
  "note_block": "Нотный блок",
  "observer": "Наблюдатель",
  "obsidian": "Обсидиан",
  "packed_ice": "Плотный лёд",
  "packed_mud": "Утрамбованная грязь",
  "painting": "Картина",
  "paper": "Бумага",
  "phantom_membrane": "Мембрана фантома",
  "piglin_head": "Голова пиглина",
  "pink_petals": "Розовые лепестки",
  "piston": "Поршень",
  "player_head": "Голова игрока",
  "podzol": "Подзол",
  "pointed_dripstone": "Капельник",
  "poisonous_potato": "Ядовитый картофель",
  "polished_andesite": "Полированный андезит",
  "polished_basalt": "Полированный базальт",
  "polished_blackstone": "Полированный чернокамень",
  "polished_deepslate": "Полированный сланец",
  "polished_diorite": "Полированный диорит",
  "polished_granite": "Полированный гранит",
  "popped_chorus_fruit": "Прожаренный плод хоруса",
  "porkchop": "Сырая свинина",
  "potato": "Картофель",
  "potion": "Зелье",
  "powder_snow_bucket": "Ведро рыхлого снега",
  "powered_rail": "Активирующие рельсы",
  "prismarine": "Призмарин",
  "prismarine_crystals": "Кристалл призмарина",
  "prismarine_shard": "Осколок призмарина",
  "pufferfish": "Иглобрюх",
  "pufferfish_bucket": "Ведро с иглобрюхом",
  "pumpkin": "Тыква",
  "pumpkin_pie": "Тыквенный пирог",
  "pumpkin_seeds": "Тыквенные семечки",
  "purple_shulker_box": "Фиолетовый шалкеровый ящик",
  "purpur_block": "Пурпурный блок",
  "purpur_pillar": "Пурпурный пилон",
  "quartz": "Кварц Нижнего мира",
  "quartz_block": "Кварцевый блок",
  "quartz_bricks": "Кварцевые кирпичи",
  "quartz_pillar": "Кварцевая колонна",
  "rabbit": "Сырая крольчатина",
  "rabbit_foot": "Кроличья лапка",
  "rabbit_hide": "Кроличья шкура",
  "rabbit_stew": "Кроличий тушёнка",
  "rail": "Рельсы",
  "raw_copper": "Необработанная медь",
  "raw_copper_block": "Блок необработанной меди",
  "raw_gold": "Необработанное золото",
  "raw_gold_block": "Блок необработанного золота",
  "raw_iron": "Необработанное железо",
  "raw_iron_block": "Блок необработанного железа",
  "recovery_compass": "Компас возврата",
  "red_mushroom": "Красный гриб",
  "red_mushroom_block": "Блок красного гриба",
  "red_sand": "Красный песок",
  "red_sandstone": "Красный песчаник",
  "redstone": "Редстоуновая пыль",
  "redstone_block": "Редстоуновый блок",
  "redstone_lamp": "Редстоуновый фонарь",
  "redstone_ore": "Редстоуновая руда",
  "redstone_torch": "Редстоуновый факел",
  "repeater": "Редстоуновый повторитель",
  "respawn_anchor": "Якорь возрождения",
  "rotten_flesh": "Гнилая плоть",
  "saddle": "Седло",
  "salmon": "Сырой лосось",
  "salmon_bucket": "Ведро с лососем",
  "sand": "Песок",
  "sandstone": "Песчаник",
  "scaffolding": "Подмостки",
  "sculk": "Скалк",
  "sculk_catalyst": "Скалковый катализатор",
  "sculk_sensor": "Скалковый сенсор",
  "sculk_shrieker": "Скалковый крикун",
  "sculk_vein": "Скалковая жила",
  "scute": "Щиток",
  "sea_lantern": "Морской фонарь",
  "sea_pickle": "Морской огурец",
  "seagrass": "Морская трава",
  "shears": "Ножницы",
  "shield": "Щит",
  "shulker_box": "Шалкеровый ящик",
  "shulker_shell": "Панцирь шалкера",
  "slime_ball": "Сгусток слизи",
  "slime_block": "Блок слизи",
  "smithing_table": "Кузнечный стол",
  "smoker": "Коптильня",
  "smooth_basalt": "Гладкий базальт",
  "smooth_quartz": "Гладкий кварцевый блок",
  "smooth_red_sandstone": "Гладкий красный песчаник",
  "smooth_sandstone": "Гладкий песчаник",
  "smooth_stone": "Гладкий камень",
  "snow": "Снег",
  "snow_block": "Блок снега",
  "snowball": "Снежок",
  "soul_campfire": "Костёр душ",
  "soul_lantern": "Фонарь душ",
  "soul_sand": "Песок душ",
  "soul_soil": "Почва душ",
  "soul_torch": "Факел душ",
  "spawn_egg": "Яйцо призыва",
  "spectral_arrow": "Спектральная стрела",
  "spider_eye": "Паучий глаз",
  "sponge": "Губка",
  "spore_blossom": "Спороцвет",
  "spyglass": "Подзорная труба",
  "stick": "Палка",
  "sticky_piston": "Липкий поршень",
  "stone": "Камень",
  "stone_axe": "Каменный топор",
  "stone_brick_slab": "Плита из каменного кирпича",
  "stone_bricks": "Каменные кирпичи",
  "stone_button": "Каменная кнопка",
  "stone_hoe": "Каменная мотыга",
  "stone_pickaxe": "Каменная кирка",
  "stone_pressure_plate": "Каменная нажимная плита",
  "stone_shovel": "Каменная лопата",
  "stone_sword": "Каменный меч",
  "stonecutter": "Камнерез",
  "string": "Нить",
  "stripped_oak_log": "Обтёсанное дубовое бревно",
  "stripped_oak_wood": "Обтёсанная дубовая древесина",
  "structure_block": "Блок структуры",
  "sugar": "Сахар",
  "sugar_cane": "Сахарный тростник",
  "sunflower": "Подсолнух",
  "suspicious_stew": "Подозрительное рагу",
  "sweet_berries": "Сладкие ягоды",
  "target": "Мишень",
  "tnt": "Динамит",
  "tnt_minecart": "Вагонетка с динамитом",
  "torch": "Факел",
  "totem_of_undying": "Тотем бессмертия",
  "trident": "Трезубец",
  "tripwire_hook": "Натяжной датчик",
  "tropical_fish": "Тропическая рыба",
  "tropical_fish_bucket": "Ведро с тропической рыбой",
  "tuff": "Туф",
  "turtle_helmet": "Черепаший панцирь",
  "twisting_vines": "Вьющиеся лианы",
  "vault": "Хранилище",
  "verdant_froglight": "Зеленоватый квакарь",
  "vine": "Лианы",
  "warped_door": "Искажённая дверь",
  "warped_fungus": "Искажённый гриб",
  "warped_fungus_on_a_stick": "Искажённый гриб на удочке",
  "warped_hyphae": "Искажённые гифы",
  "warped_nylium": "Искажённый нилий",
  "warped_planks": "Искажённые доски",
  "warped_roots": "Искажённые корни",
  "warped_slab": "Искажённая плита",
  "warped_stairs": "Искажённые ступеньки",
  "warped_stem": "Искажённый стебель",
  "warped_trapdoor": "Искажённый люк",
  "water_bucket": "Ведро воды",
  "waxed_copper_block": "Вощёный медный блок",
  "waxed_cut_copper": "Вощёный резный медный блок",
  "weathered_copper": "Состаренная медь",
  "web": "Паутина",
  "weeping_vines": "Плачущие лианы",
  "wet_sponge": "Мокрая губка",
  "wheat": "Пшеница",
  "wheat_seeds": "Семена пшеницы",
  "white_banner": "Белый флаг",
  "white_bed": "Белая кровать",
  "white_candle": "Белая свеча",
  "white_carpet": "Белый ковёр",
  "white_concrete": "Белый бетон",
  "white_dye": "Белый краситель",
  "white_stained_glass": "Белое стекло",
  "white_wool": "Белая шерсть",
  "wind_charge": "Заряд ветра",
  "wither_rose": "Роза Иссушителя",
  "wither_skeleton_skull": "Череп скелета-иссушителя",
  "wooden_axe": "Деревянный топор",
  "wooden_hoe": "Деревянная мотыга",
  "wooden_pickaxe": "Деревянная кирка",
  "wooden_shovel": "Деревянная лопата",
  "wooden_sword": "Деревянный меч",
  "written_book": "Завершённая книга",
  "yellow_banner": "Жёлтый флаг",
  "yellow_bed": "Жёлтая кровать",
  "yellow_candle": "Жёлтая свеча",
  "yellow_carpet": "Жёлтый ковёр",
  "yellow_concrete": "Жёлтый бетон",
  "yellow_dye": "Жёлтый краситель",
  "yellow_stained_glass": "Жёлтое стекло",
  "yellow_wool": "Жёлтая шерсть",
  "absorption": "Absorption",
  "acacia_boat": "Акациевая лодка",
  "acacia_button": "Акациевая кнопка",
  "acacia_chest_boat": "Акациевая лодка с сундуком",
  "acacia_door": "Акациевая дверь",
  "acacia_fence": "Акациевый забор",
  "acacia_fence_gate": "Акациевая калитка",
  "acacia_hanging_sign": "Акациевая подвесная табличка",
  "acacia_leaves": "Листья (акациевый)",
  "acacia_log": "Акациевое бревно",
  "acacia_planks": "Акациевые доски",
  "acacia_pressure_plate": "Акациевая нажимная плита",
  "acacia_sapling": "Саженец (акациевый)",
  "acacia_sign": "Акациевая табличка",
  "acacia_slab": "Акациевая плита",
  "acacia_stairs": "Акациевые ступеньки",
  "acacia_trapdoor": "Акациевый люк",
  "acacia_wood": "Акациевая древесина",
  "activator_rail": "Activator rail",
  "allay_spawn_egg": "Яйцо призыва (allay)",
  "allium": "Allium",
  "amethyst_block": "Amethyst block",
  "amethyst_cluster": "Amethyst cluster",
  "amethyst_shard": "Amethyst shard",
  "ancient_debris": "Ancient debris",
  "andesite": "Andesite",
  "andesite_slab": "Andesite slab",
  "andesite_stairs": "Andesite stairs",
  "andesite_wall": "Andesite wall",
  "angler_pottery_sherd": "Глиняный черепок (angler)",
  "anvil": "Anvil",
  "archer_pottery_sherd": "Глиняный черепок (archer)",
  "armadillo_scute": "Armadillo scute",
  "armadillo_spawn_egg": "Яйцо призыва (armadillo)",
  "armor_stand": "Armor stand",
  "arms_up_pottery_sherd": "Глиняный черепок (arms up)",
  "axolotl_bucket": "Axolotl bucket",
  "axolotl_spawn_egg": "Яйцо призыва (axolotl)",
  "azalea": "Azalea",
  "azalea_leaves": "Azalea leaves",
  "azure_bluet": "Azure bluet",
  "bad_luck": "Bad luck",
  "bamboo_block": "Bamboo block",
  "bamboo_button": "Бамбуковая кнопка",
  "bamboo_chest_raft": "Bamboo chest raft",
  "bamboo_door": "Бамбуковая дверь",
  "bamboo_fence": "Бамбуковый забор",
  "bamboo_fence_gate": "Бамбуковая калитка",
  "bamboo_hanging_sign": "Бамбуковая подвесная табличка",
  "bamboo_mosaic": "Bamboo mosaic",
  "bamboo_mosaic_slab": "Bamboo mosaic slab",
  "bamboo_mosaic_stairs": "Bamboo mosaic stairs",
  "bamboo_planks": "Бамбуковые доски",
  "bamboo_pressure_plate": "Бамбуковая нажимная плита",
  "bamboo_raft": "Bamboo raft",
  "bamboo_sign": "Бамбуковая табличка",
  "bamboo_slab": "Бамбуковая плита",
  "bamboo_stairs": "Бамбуковые ступеньки",
  "bamboo_trapdoor": "Бамбуковый люк",
  "basis_big": "Basis big",
  "basis_splash_big": "Basis splash big",
  "bat_spawn_egg": "Яйцо призыва (bat)",
  "bee_spawn_egg": "Яйцо призыва (bee)",
  "big_dripleaf": "Big dripleaf",
  "birch_boat": "Берёзовая лодка",
  "birch_button": "Берёзовая кнопка",
  "birch_chest_boat": "Берёзовая лодка с сундуком",
  "birch_door": "Берёзовая дверь",
  "birch_fence": "Берёзовый забор",
  "birch_fence_gate": "Берёзовая калитка",
  "birch_hanging_sign": "Берёзовая подвесная табличка",
  "birch_leaves": "Листья (берёзовый)",
  "birch_log": "Берёзовое бревно",
  "birch_planks": "Берёзовые доски",
  "birch_pressure_plate": "Берёзовая нажимная плита",
  "birch_sapling": "Саженец (берёзовый)",
  "birch_sign": "Берёзовая табличка",
  "birch_slab": "Берёзовая плита",
  "birch_stairs": "Берёзовые ступеньки",
  "birch_trapdoor": "Берёзовый люк",
  "birch_wood": "Берёзовая древесина",
  "blackstone": "Blackstone",
  "blackstone_slab": "Blackstone slab",
  "blackstone_stairs": "Blackstone stairs",
  "blackstone_wall": "Blackstone wall",
  "black_banner": "Чёрный флаг",
  "black_bed": "Чёрная кровать",
  "black_bundle": "Чёрный мешок",
  "black_candle": "Чёрная свеча",
  "black_carpet": "Чёрный ковёр",
  "black_concrete": "Чёрный бетон",
  "black_concrete_powder": "Чёрный сухой бетон",
  "black_dye": "Чёрный краситель",
  "black_glazed_terracotta": "Чёрная глазурованная керамика",
  "black_shulker_box": "Чёрный шалкеровый ящик",
  "black_stained_glass": "Чёрное стекло",
  "black_stained_glass_pane": "Чёрная стеклянная панель",
  "black_terracotta": "Чёрная керамика",
  "black_wool": "Чёрная шерсть",
  "blade_pottery_sherd": "Глиняный черепок (blade)",
  "blast_furnace": "Blast furnace",
  "blaze_spawn_egg": "Яйцо призыва (blaze)",
  "blue_banner": "Синий флаг",
  "blue_bed": "Синяя кровать",
  "blue_bundle": "Синий мешок",
  "blue_candle": "Синяя свеча",
  "blue_carpet": "Синий ковёр",
  "blue_concrete": "Синий бетон",
  "blue_concrete_powder": "Синий сухой бетон",
  "blue_dye": "Синий краситель",
  "blue_glazed_terracotta": "Синяя глазурованная керамика",
  "blue_ice": "Blue ice",
  "blue_indicator_big": "Blue indicator big",
  "blue_indicator_splash_big": "Blue indicator splash big",
  "blue_orchid": "Blue orchid",
  "blue_potion": "Blue potion",
  "blue_shulker_box": "Синий шалкеровый ящик",
  "blue_stained_glass": "Синее стекло",
  "blue_stained_glass_pane": "Синяя стеклянная панель",
  "blue_terracotta": "Синяя керамика",
  "blue_wool": "Синяя шерсть",
  "bogged_spawn_egg": "Яйцо призыва (bogged)",
  "bolt_armor_trim_smithing_template": "Кузнечный шаблон (bolt armor trim)",
  "bordure_indented_banner_pattern": "Узор флага (bordure indented)",
  "brain_coral": "Brain coral",
  "brain_coral_block": "Brain coral block",
  "brain_coral_fan": "Brain coral fan",
  "breeze_spawn_egg": "Яйцо призыва (breeze)",
  "brewer_pottery_sherd": "Глиняный черепок (brewer)",
  "brick_slab": "Brick slab",
  "brick_stairs": "Brick stairs",
  "brick_wall": "Brick wall",
  "brown_banner": "Коричневый флаг",
  "brown_bed": "Коричневая кровать",
  "brown_bundle": "Коричневый мешок",
  "brown_candle": "Коричневая свеча",
  "brown_carpet": "Коричневый ковёр",
  "brown_concrete": "Коричневый бетон",
  "brown_concrete_powder": "Коричневый сухой бетон",
  "brown_dye": "Коричневый краситель",
  "brown_glazed_terracotta": "Коричневая глазурованная керамика",
  "brown_mushroom": "Brown mushroom",
  "brown_mushroom_block": "Brown mushroom block",
  "brown_shulker_box": "Коричневый шалкеровый ящик",
  "brown_stained_glass": "Коричневое стекло",
  "brown_stained_glass_pane": "Коричневая стеклянная панель",
  "brown_terracotta": "Коричневая керамика",
  "brown_wool": "Коричневая шерсть",
  "bubble_coral": "Bubble coral",
  "bubble_coral_block": "Bubble coral block",
  "bubble_coral_fan": "Bubble coral fan",
  "budding_amethyst": "Budding amethyst",
  "burn_pottery_sherd": "Глиняный черепок (burn)",
  "calibrated_sculk_sensor": "Calibrated sculk sensor",
  "camel_spawn_egg": "Яйцо призыва (camel)",
  "cat_spawn_egg": "Яйцо призыва (cat)",
  "cave_spider_spawn_egg": "Яйцо призыва (cave spider)",
  "chainmail_boots": "Chainmail boots",
  "chainmail_chestplate": "Chainmail chestplate",
  "chainmail_helmet": "Chainmail helmet",
  "chainmail_leggings": "Chainmail leggings",
  "chain_command_block": "Chain command block",
  "cherry_boat": "Вишнёвая лодка",
  "cherry_button": "Вишнёвая кнопка",
  "cherry_chest_boat": "Вишнёвая лодка с сундуком",
  "cherry_door": "Вишнёвая дверь",
  "cherry_fence": "Вишнёвый забор",
  "cherry_fence_gate": "Вишнёвая калитка",
  "cherry_hanging_sign": "Вишнёвая подвесная табличка",
  "cherry_leaves": "Листья (вишнёвый)",
  "cherry_log": "Вишнёвое бревно",
  "cherry_planks": "Вишнёвые доски",
  "cherry_pressure_plate": "Вишнёвая нажимная плита",
  "cherry_sapling": "Саженец (вишнёвый)",
  "cherry_sign": "Вишнёвая табличка",
  "cherry_slab": "Вишнёвая плита",
  "cherry_stairs": "Вишнёвые ступеньки",
  "cherry_trapdoor": "Вишнёвый люк",
  "cherry_wood": "Вишнёвая древесина",
  "chicken_spawn_egg": "Яйцо призыва (chicken)",
  "chipped_anvil": "Chipped anvil",
  "chiseled_copper": "Chiseled copper",
  "chiseled_deepslate": "Chiseled deepslate",
  "chiseled_nether_bricks": "Chiseled nether bricks",
  "chiseled_polished_blackstone": "Chiseled polished blackstone",
  "chiseled_quartz_block": "Chiseled quartz block",
  "chiseled_red_sandstone": "Chiseled red sandstone",
  "chiseled_resin_bricks": "Chiseled resin bricks",
  "chiseled_sandstone": "Chiseled sandstone",
  "chiseled_stone_bricks": "Chiseled stone bricks",
  "chiseled_tuff": "Chiseled tuff",
  "chiseled_tuff_bricks": "Chiseled tuff bricks",
  "closed_eyeblossom": "Closed eyeblossom",
  "coast_armor_trim_smithing_template": "Кузнечный шаблон (coast armor trim)",
  "cobbled_deepslate": "Cobbled deepslate",
  "cobbled_deepslate_slab": "Cobbled deepslate slab",
  "cobbled_deepslate_stairs": "Cobbled deepslate stairs",
  "cobbled_deepslate_wall": "Cobbled deepslate wall",
  "cobblestone_slab": "Cobblestone slab",
  "cobblestone_stairs": "Cobblestone stairs",
  "cobblestone_wall": "Cobblestone wall",
  "cod_spawn_egg": "Яйцо призыва (cod)",
  "command_block_minecart": "Command block minecart",
  "concussion": "Concussion",
  "conduit_power": "Conduit power",
  "cow_spawn_egg": "Яйцо призыва (cow)",
  "cracked_deepslate_bricks": "Cracked deepslate bricks",
  "cracked_deepslate_tiles": "Cracked deepslate tiles",
  "cracked_nether_bricks": "Cracked nether bricks",
  "cracked_polished_blackstone_bricks": "Cracked polished blackstone bricks",
  "cracked_stone_bricks": "Cracked stone bricks",
  "crafter": "Crafter",
  "creaking_heart": "Creaking heart",
  "creaking_spawn_egg": "Яйцо призыва (creaking)",
  "creeper_banner_pattern": "Узор флага (creeper)",
  "creeper_spawn_egg": "Яйцо призыва (creeper)",
  "crimson_button": "Багровая кнопка",
  "crimson_door": "Багровая дверь",
  "crimson_fence": "Багровый забор",
  "crimson_fence_gate": "Багровая калитка",
  "crimson_fungus": "Crimson fungus",
  "crimson_hanging_sign": "Багровая подвесная табличка",
  "crimson_hyphae": "Crimson hyphae",
  "crimson_nylium": "Crimson nylium",
  "crimson_planks": "Багровые доски",
  "crimson_pressure_plate": "Багровая нажимная плита",
  "crimson_roots": "Crimson roots",
  "crimson_sign": "Багровая табличка",
  "crimson_slab": "Багровая плита",
  "crimson_stairs": "Багровые ступеньки",
  "crimson_stem": "Crimson stem",
  "crimson_trapdoor": "Багровый люк",
  "cut_copper": "Cut copper",
  "cut_copper_slab": "Cut copper slab",
  "cut_copper_stairs": "Cut copper stairs",
  "cut_red_sandstone": "Cut red sandstone",
  "cut_red_sandstone_slab": "Cut red sandstone slab",
  "cut_sandstone": "Cut sandstone",
  "cut_sandstone_slab": "Cut sandstone slab",
  "cyan_banner": "Бирюзовый флаг",
  "cyan_bed": "Бирюзовая кровать",
  "cyan_bundle": "Бирюзовый мешок",
  "cyan_candle": "Бирюзовая свеча",
  "cyan_carpet": "Бирюзовый ковёр",
  "cyan_concrete": "Бирюзовый бетон",
  "cyan_concrete_powder": "Бирюзовый сухой бетон",
  "cyan_dye": "Бирюзовый краситель",
  "cyan_glazed_terracotta": "Бирюзовая глазурованная керамика",
  "cyan_shulker_box": "Бирюзовый шалкеровый ящик",
  "cyan_stained_glass": "Бирюзовое стекло",
  "cyan_stained_glass_pane": "Бирюзовая стеклянная панель",
  "cyan_terracotta": "Бирюзовая керамика",
  "cyan_wool": "Бирюзовая шерсть",
  "damaged_anvil": "Damaged anvil",
  "danger_pottery_sherd": "Глиняный черепок (danger)",
  "darkness": "Darkness",
  "dark_oak_boat": "Тёмно-дубовая лодка",
  "dark_oak_button": "Тёмно-дубовая кнопка",
  "dark_oak_chest_boat": "Тёмно-дубовая лодка с сундуком",
  "dark_oak_door": "Тёмно-дубовая дверь",
  "dark_oak_fence": "Тёмно-дубовый забор",
  "dark_oak_fence_gate": "Тёмно-дубовая калитка",
  "dark_oak_hanging_sign": "Тёмно-дубовая подвесная табличка",
  "dark_oak_leaves": "Листья (тёмно-дубовый)",
  "dark_oak_log": "Тёмно-дубовое бревно",
  "dark_oak_planks": "Тёмно-дубовые доски",
  "dark_oak_pressure_plate": "Тёмно-дубовая нажимная плита",
  "dark_oak_sapling": "Саженец (тёмно-дубовый)",
  "dark_oak_sign": "Тёмно-дубовая табличка",
  "dark_oak_slab": "Тёмно-дубовая плита",
  "dark_oak_stairs": "Тёмно-дубовые ступеньки",
  "dark_oak_trapdoor": "Тёмно-дубовый люк",
  "dark_oak_wood": "Тёмно-дубовая древесина",
  "dark_prismarine": "Dark prismarine",
  "dark_prismarine_slab": "Dark prismarine slab",
  "dark_prismarine_stairs": "Dark prismarine stairs",
  "dead_brain_coral": "Dead brain coral",
  "dead_brain_coral_block": "Dead brain coral block",
  "dead_brain_coral_fan": "Dead brain coral fan",
  "dead_bubble_coral": "Dead bubble coral",
  "dead_bubble_coral_block": "Dead bubble coral block",
  "dead_bubble_coral_fan": "Dead bubble coral fan",
  "dead_fire_coral": "Dead fire coral",
  "dead_fire_coral_block": "Dead fire coral block",
  "dead_fire_coral_fan": "Dead fire coral fan",
  "dead_horn_coral": "Dead horn coral",
  "dead_horn_coral_block": "Dead horn coral block",
  "dead_horn_coral_fan": "Dead horn coral fan",
  "dead_tube_coral": "Dead tube coral",
  "dead_tube_coral_block": "Dead tube coral block",
  "dead_tube_coral_fan": "Dead tube coral fan",
  "deepslate_bricks": "Deepslate bricks",
  "deepslate_brick_slab": "Deepslate brick slab",
  "deepslate_brick_stairs": "Deepslate brick stairs",
  "deepslate_brick_wall": "Deepslate brick wall",
  "deepslate_coal_ore": "Deepslate coal ore",
  "deepslate_copper_ore": "Deepslate copper ore",
  "deepslate_diamond_ore": "Deepslate diamond ore",
  "deepslate_emerald_ore": "Deepslate emerald ore",
  "deepslate_gold_ore": "Deepslate gold ore",
  "deepslate_iron_ore": "Deepslate iron ore",
  "deepslate_lapis_ore": "Deepslate lapis ore",
  "deepslate_redstone_ore": "Deepslate redstone ore",
  "deepslate_tiles": "Deepslate tiles",
  "deepslate_tile_slab": "Deepslate tile slab",
  "deepslate_tile_stairs": "Deepslate tile stairs",
  "deepslate_tile_wall": "Deepslate tile wall",
  "diorite_slab": "Diorite slab",
  "diorite_stairs": "Diorite stairs",
  "diorite_wall": "Diorite wall",
  "disc_fragment_5": "Disc fragment 5",
  "dolphins_grace": "Dolphins grace",
  "dolphin_spawn_egg": "Яйцо призыва (dolphin)",
  "donkey_spawn_egg": "Яйцо призыва (donkey)",
  "drowned_spawn_egg": "Яйцо призыва (drowned)",
  "dune_armor_trim_smithing_template": "Кузнечный шаблон (dune armor trim)",
  "eater": "Eater",
  "elder_guardian_spawn_egg": "Яйцо призыва (elder guardian)",
  "enderman_spawn_egg": "Яйцо призыва (enderman)",
  "endermite_spawn_egg": "Яйцо призыва (endermite)",
  "ender_dragon_spawn_egg": "Яйцо призыва (ender dragon)",
  "end_stone_bricks": "End stone bricks",
  "end_stone_brick_slab": "End stone brick slab",
  "end_stone_brick_stairs": "End stone brick stairs",
  "end_stone_brick_wall": "End stone brick wall",
  "evoker_spawn_egg": "Яйцо призыва (evoker)",
  "explorer_pottery_sherd": "Глиняный черепок (explorer)",
  "exposed_chiseled_copper": "Exposed chiseled copper",
  "exposed_copper": "Exposed copper",
  "exposed_copper_bulb": "Exposed copper bulb",
  "exposed_copper_door": "Exposed copper door",
  "exposed_copper_grate": "Exposed copper grate",
  "exposed_copper_trapdoor": "Exposed copper trapdoor",
  "exposed_cut_copper": "Exposed cut copper",
  "exposed_cut_copper_slab": "Exposed cut copper slab",
  "exposed_cut_copper_stairs": "Exposed cut copper stairs",
  "eye_armor_trim_smithing_template": "Кузнечный шаблон (eye armor trim)",
  "field_masoned_banner_pattern": "Узор флага (field masoned)",
  "filled_map": "Filled map",
  "fireness": "Fireness",
  "fire_coral": "Fire coral",
  "fire_coral_block": "Fire coral block",
  "fire_coral_fan": "Fire coral fan",
  "fire_resistance": "Fire resistance",
  "flowering_azalea": "Flowering azalea",
  "flowering_azalea_leaves": "Flowering azalea leaves",
  "flower_banner_pattern": "Узор флага (flower)",
  "flow_armor_trim_smithing_template": "Кузнечный шаблон (flow armor trim)",
  "flow_banner_pattern": "Узор флага (flow)",
  "flow_pottery_sherd": "Глиняный черепок (flow)",
  "fox_spawn_egg": "Яйцо призыва (fox)",
  "friend_pottery_sherd": "Глиняный черепок (friend)",
  "frogspawn": "Frogspawn",
  "frog_spawn_egg": "Яйцо призыва (frog)",
  "ghast_spawn_egg": "Яйцо призыва (ghast)",
  "globe_banner_pattern": "Узор флага (globe)",
  "glow_lichen": "Glow lichen",
  "glow_squid_spawn_egg": "Яйцо призыва (glow squid)",
  "goat_spawn_egg": "Яйцо призыва (goat)",
  "granite_slab": "Granite slab",
  "granite_stairs": "Granite stairs",
  "granite_wall": "Granite wall",
  "gravitational_fluctuations": "Gravitational fluctuations",
  "gray_banner": "Серый флаг",
  "gray_bed": "Серая кровать",
  "gray_bundle": "Серый мешок",
  "gray_candle": "Серая свеча",
  "gray_carpet": "Серый ковёр",
  "gray_concrete": "Серый бетон",
  "gray_concrete_powder": "Серый сухой бетон",
  "gray_dye": "Серый краситель",
  "gray_glazed_terracotta": "Серая глазурованная керамика",
  "gray_shulker_box": "Серый шалкеровый ящик",
  "gray_stained_glass": "Серое стекло",
  "gray_stained_glass_pane": "Серая стеклянная панель",
  "gray_terracotta": "Серая керамика",
  "gray_wool": "Серая шерсть",
  "green_banner": "Зелёный флаг",
  "green_bed": "Зелёная кровать",
  "green_bundle": "Зелёный мешок",
  "green_candle": "Зелёная свеча",
  "green_carpet": "Зелёный ковёр",
  "green_concrete": "Зелёный бетон",
  "green_concrete_powder": "Зелёный сухой бетон",
  "green_dye": "Зелёный краситель",
  "green_glazed_terracotta": "Зелёная глазурованная керамика",
  "green_indicator_big": "Green indicator big",
  "green_indicator_splash_big": "Green indicator splash big",
  "green_shulker_box": "Зелёный шалкеровый ящик",
  "green_stained_glass": "Зелёное стекло",
  "green_stained_glass_pane": "Зелёная стеклянная панель",
  "green_terracotta": "Зелёная керамика",
  "green_wool": "Зелёная шерсть",
  "guardian_spawn_egg": "Яйцо призыва (guardian)",
  "guster_banner_pattern": "Узор флага (guster)",
  "guster_pottery_sherd": "Глиняный черепок (guster)",
  "haste": "Haste",
  "heartbreak_pottery_sherd": "Глиняный черепок (heartbreak)",
  "heart_pottery_sherd": "Глиняный черепок (heart)",
  "heavy_weighted_pressure_plate": "Heavy weighted pressure plate",
  "hero_of_the_village": "Hero of the village",
  "hoglin_spawn_egg": "Яйцо призыва (hoglin)",
  "horn_coral": "Horn coral",
  "horn_coral_block": "Horn coral block",
  "horn_coral_fan": "Horn coral fan",
  "horse_spawn_egg": "Яйцо призыва (horse)",
  "host_armor_trim_smithing_template": "Кузнечный шаблон (host armor trim)",
  "howl_pottery_sherd": "Глиняный черепок (howl)",
  "hunger": "Hunger",
  "husk_spawn_egg": "Яйцо призыва (husk)",
  "infested": "Infested",
  "infested_chiseled_stone_bricks": "Infested chiseled stone bricks",
  "infested_cobblestone": "Infested cobblestone",
  "infested_cracked_stone_bricks": "Infested cracked stone bricks",
  "infested_deepslate": "Infested deepslate",
  "infested_mossy_stone_bricks": "Infested mossy stone bricks",
  "infested_stone": "Infested stone",
  "infested_stone_bricks": "Infested stone bricks",
  "instant_damage": "Instant damage",
  "instant_health": "Instant health",
  "invisibility": "Invisibility",
  "iron_golem_spawn_egg": "Яйцо призыва (iron golem)",
  "jigsaw": "Jigsaw",
  "jump_boost": "Jump boost",
  "jungle_boat": "Тропическая лодка",
  "jungle_button": "Тропическая кнопка",
  "jungle_chest_boat": "Тропическая лодка с сундуком",
  "jungle_door": "Тропическая дверь",
  "jungle_fence": "Тропический забор",
  "jungle_fence_gate": "Тропическая калитка",
  "jungle_hanging_sign": "Тропическая подвесная табличка",
  "jungle_leaves": "Листья (тропический)",
  "jungle_log": "Тропическое бревно",
  "jungle_planks": "Тропические доски",
  "jungle_pressure_plate": "Тропическая нажимная плита",
  "jungle_sapling": "Саженец (тропический)",
  "jungle_sign": "Тропическая табличка",
  "jungle_slab": "Тропическая плита",
  "jungle_stairs": "Тропические ступеньки",
  "jungle_trapdoor": "Тропический люк",
  "jungle_wood": "Тропическая древесина",
  "knowledge_book": "Knowledge book",
  "large_amethyst_bud": "Large amethyst bud",
  "large_fern": "Large fern",
  "lava_bucket": "Lava bucket",
  "levitation": "Levitation",
  "light_blue_banner": "Голубой флаг",
  "light_blue_bed": "Голубая кровать",
  "light_blue_bundle": "Голубой мешок",
  "light_blue_candle": "Голубая свеча",
  "light_blue_carpet": "Голубой ковёр",
  "light_blue_concrete": "Голубой бетон",
  "light_blue_concrete_powder": "Голубой сухой бетон",
  "light_blue_dye": "Голубой краситель",
  "light_blue_glazed_terracotta": "Голубая глазурованная керамика",
  "light_blue_shulker_box": "Голубой шалкеровый ящик",
  "light_blue_stained_glass": "Голубое стекло",
  "light_blue_stained_glass_pane": "Голубая стеклянная панель",
  "light_blue_terracotta": "Голубая керамика",
  "light_blue_wool": "Голубая шерсть",
  "light_gray_banner": "Светло-серый флаг",
  "light_gray_bed": "Светло-серая кровать",
  "light_gray_bundle": "Светло-серый мешок",
  "light_gray_candle": "Светло-серая свеча",
  "light_gray_carpet": "Светло-серый ковёр",
  "light_gray_concrete": "Светло-серый бетон",
  "light_gray_concrete_powder": "Светло-серый сухой бетон",
  "light_gray_dye": "Светло-серый краситель",
  "light_gray_glazed_terracotta": "Светло-серая глазурованная керамика",
  "light_gray_shulker_box": "Светло-серый шалкеровый ящик",
  "light_gray_stained_glass": "Светло-серое стекло",
  "light_gray_stained_glass_pane": "Светло-серая стеклянная панель",
  "light_gray_terracotta": "Светло-серая керамика",
  "light_gray_wool": "Светло-серая шерсть",
  "light_weighted_pressure_plate": "Light weighted pressure plate",
  "lilac": "Lilac",
  "lily_of_the_valley": "Lily of the valley",
  "lime_banner": "Лаймовый флаг",
  "lime_bed": "Лаймовая кровать",
  "lime_bundle": "Лаймовый мешок",
  "lime_candle": "Лаймовая свеча",
  "lime_carpet": "Лаймовый ковёр",
  "lime_concrete": "Лаймовый бетон",
  "lime_concrete_powder": "Лаймовый сухой бетон",
  "lime_dye": "Лаймовый краситель",
  "lime_glazed_terracotta": "Лаймовая глазурованная керамика",
  "lime_shulker_box": "Лаймовый шалкеровый ящик",
  "lime_stained_glass": "Лаймовое стекло",
  "lime_stained_glass_pane": "Лаймовая стеклянная панель",
  "lime_terracotta": "Лаймовая керамика",
  "lime_wool": "Лаймовая шерсть",
  "lingering_potion": "Lingering potion",
  "llama_spawn_egg": "Яйцо призыва (llama)",
  "madness": "Madness",
  "magenta_banner": "Пурпурный флаг",
  "magenta_bed": "Пурпурная кровать",
  "magenta_bundle": "Пурпурный мешок",
  "magenta_candle": "Пурпурная свеча",
  "magenta_carpet": "Пурпурный ковёр",
  "magenta_concrete": "Пурпурный бетон",
  "magenta_concrete_powder": "Пурпурный сухой бетон",
  "magenta_dye": "Пурпурный краситель",
  "magenta_glazed_terracotta": "Пурпурная глазурованная керамика",
  "magenta_shulker_box": "Пурпурный шалкеровый ящик",
  "magenta_stained_glass": "Пурпурное стекло",
  "magenta_stained_glass_pane": "Пурпурная стеклянная панель",
  "magenta_terracotta": "Пурпурная керамика",
  "magenta_wool": "Пурпурная шерсть",
  "magma_cube_spawn_egg": "Яйцо призыва (magma cube)",
  "mangrove_boat": "Мангровая лодка",
  "mangrove_button": "Мангровая кнопка",
  "mangrove_chest_boat": "Мангровая лодка с сундуком",
  "mangrove_door": "Мангровая дверь",
  "mangrove_fence": "Мангровый забор",
  "mangrove_fence_gate": "Мангровая калитка",
  "mangrove_hanging_sign": "Мангровая подвесная табличка",
  "mangrove_leaves": "Листья (мангровый)",
  "mangrove_log": "Мангровое бревно",
  "mangrove_planks": "Мангровые доски",
  "mangrove_pressure_plate": "Мангровая нажимная плита",
  "mangrove_propagule": "Mangrove propagule",
  "mangrove_sign": "Мангровая табличка",
  "mangrove_slab": "Мангровая плита",
  "mangrove_stairs": "Мангровые ступеньки",
  "mangrove_trapdoor": "Мангровый люк",
  "mangrove_wood": "Мангровая древесина",
  "medium_amethyst_bud": "Medium amethyst bud",
  "miner_pottery_sherd": "Глиняный черепок (miner)",
  "mining_fatigue": "Mining fatigue",
  "mojang_banner_pattern": "Узор флага (mojang)",
  "mooshroom_spawn_egg": "Яйцо призыва (mooshroom)",
  "mossy_cobblestone_slab": "Mossy cobblestone slab",
  "mossy_cobblestone_stairs": "Mossy cobblestone stairs",
  "mossy_cobblestone_wall": "Mossy cobblestone wall",
  "mossy_stone_bricks": "Mossy stone bricks",
  "mossy_stone_brick_slab": "Mossy stone brick slab",
  "mossy_stone_brick_stairs": "Mossy stone brick stairs",
  "mossy_stone_brick_wall": "Mossy stone brick wall",
  "mourner_pottery_sherd": "Глиняный черепок (mourner)",
  "muddy_mangrove_roots": "Muddy mangrove roots",
  "mud_brick_slab": "Mud brick slab",
  "mud_brick_stairs": "Mud brick stairs",
  "mud_brick_wall": "Mud brick wall",
  "mule_spawn_egg": "Яйцо призыва (mule)",
  "music_disc_11": "Музыкальная пластинка (11)",
  "music_disc_13": "Музыкальная пластинка (13)",
  "music_disc_5": "Музыкальная пластинка (5)",
  "music_disc_blocks": "Музыкальная пластинка (blocks)",
  "music_disc_cat": "Музыкальная пластинка (cat)",
  "music_disc_chirp": "Музыкальная пластинка (chirp)",
  "music_disc_creator": "Музыкальная пластинка (creator)",
  "music_disc_creator_music_box": "Музыкальная пластинка (creator_music_box)",
  "music_disc_far": "Музыкальная пластинка (far)",
  "music_disc_mall": "Музыкальная пластинка (mall)",
  "music_disc_mellohi": "Музыкальная пластинка (mellohi)",
  "music_disc_otherside": "Музыкальная пластинка (otherside)",
  "music_disc_pigstep": "Музыкальная пластинка (pigstep)",
  "music_disc_precipice": "Музыкальная пластинка (precipice)",
  "music_disc_relic": "Музыкальная пластинка (relic)",
  "music_disc_stal": "Музыкальная пластинка (stal)",
  "music_disc_strad": "Музыкальная пластинка (strad)",
  "music_disc_wait": "Музыкальная пластинка (wait)",
  "music_disc_ward": "Музыкальная пластинка (ward)",
  "nausea": "Nausea",
  "netherite_upgrade_smithing_template": "Кузнечный шаблон (netherite upgrade)",
  "nether_brick_fence": "Nether brick fence",
  "nether_brick_slab": "Nether brick slab",
  "nether_brick_stairs": "Nether brick stairs",
  "nether_brick_wall": "Nether brick wall",
  "nether_sprouts": "Nether sprouts",
  "night_vision": "Night vision",
  "oak_boat": "Дубовая лодка",
  "oak_button": "Дубовая кнопка",
  "oak_chest_boat": "Дубовая лодка с сундуком",
  "oak_door": "Дубовая дверь",
  "oak_fence": "Дубовый забор",
  "oak_fence_gate": "Дубовая калитка",
  "oak_hanging_sign": "Дубовая подвесная табличка",
  "oak_leaves": "Листья (дубовый)",
  "oak_log": "Дубовое бревно",
  "oak_planks": "Дубовые доски",
  "oak_pressure_plate": "Дубовая нажимная плита",
  "oak_sapling": "Саженец (дубовый)",
  "oak_sign": "Дубовая табличка",
  "oak_slab": "Дубовая плита",
  "oak_stairs": "Дубовые ступеньки",
  "oak_trapdoor": "Дубовый люк",
  "oak_wood": "Дубовая древесина",
  "ocelot_spawn_egg": "Яйцо призыва (ocelot)",
  "ochre_froglight": "Ochre froglight",
  "ominous_bottle": "Ominous bottle",
  "ominous_trial_key": "Ominous trial key",
  "open_eyeblossom": "Open eyeblossom",
  "orange_banner": "Оранжевый флаг",
  "orange_bed": "Оранжевая кровать",
  "orange_bundle": "Оранжевый мешок",
  "orange_candle": "Оранжевая свеча",
  "orange_carpet": "Оранжевый ковёр",
  "orange_concrete": "Оранжевый бетон",
  "orange_concrete_powder": "Оранжевый сухой бетон",
  "orange_dye": "Оранжевый краситель",
  "orange_glazed_terracotta": "Оранжевая глазурованная керамика",
  "orange_potion": "Orange potion",
  "orange_shulker_box": "Оранжевый шалкеровый ящик",
  "orange_stained_glass": "Оранжевое стекло",
  "orange_stained_glass_pane": "Оранжевая стеклянная панель",
  "orange_terracotta": "Оранжевая керамика",
  "orange_tulip": "Orange tulip",
  "orange_wool": "Оранжевая шерсть",
  "oxeye_daisy": "Oxeye daisy",
  "oxidized_chiseled_copper": "Oxidized chiseled copper",
  "oxidized_copper": "Oxidized copper",
  "oxidized_copper_bulb": "Oxidized copper bulb",
  "oxidized_copper_door": "Oxidized copper door",
  "oxidized_copper_grate": "Oxidized copper grate",
  "oxidized_copper_trapdoor": "Oxidized copper trapdoor",
  "oxidized_cut_copper": "Oxidized cut copper",
  "oxidized_cut_copper_slab": "Oxidized cut copper slab",
  "oxidized_cut_copper_stairs": "Oxidized cut copper stairs",
  "pale_hanging_moss": "Pale hanging moss",
  "pale_moss_block": "Pale moss block",
  "pale_moss_carpet": "Pale moss carpet",
  "pale_oak_boat": "Бледно-дубовая лодка",
  "pale_oak_button": "Бледно-дубовая кнопка",
  "pale_oak_chest_boat": "Бледно-дубовая лодка с сундуком",
  "pale_oak_door": "Бледно-дубовая дверь",
  "pale_oak_fence": "Бледно-дубовый забор",
  "pale_oak_fence_gate": "Бледно-дубовая калитка",
  "pale_oak_hanging_sign": "Бледно-дубовая подвесная табличка",
  "pale_oak_leaves": "Листья (бледно-дубовый)",
  "pale_oak_log": "Бледно-дубовое бревно",
  "pale_oak_planks": "Бледно-дубовые доски",
  "pale_oak_pressure_plate": "Бледно-дубовая нажимная плита",
  "pale_oak_sapling": "Саженец (бледно-дубовый)",
  "pale_oak_sign": "Бледно-дубовая табличка",
  "pale_oak_slab": "Бледно-дубовая плита",
  "pale_oak_stairs": "Бледно-дубовые ступеньки",
  "pale_oak_trapdoor": "Бледно-дубовый люк",
  "pale_oak_wood": "Бледно-дубовая древесина",
  "panda_spawn_egg": "Яйцо призыва (panda)",
  "parrot_spawn_egg": "Яйцо призыва (parrot)",
  "pearlescent_froglight": "Pearlescent froglight",
  "peony": "Peony",
  "persistance": "Persistance",
  "petrified_oak_slab": "Petrified oak slab",
  "phantom_spawn_egg": "Яйцо призыва (phantom)",
  "piglin_banner_pattern": "Узор флага (piglin)",
  "piglin_brute_spawn_egg": "Яйцо призыва (piglin brute)",
  "piglin_spawn_egg": "Яйцо призыва (piglin)",
  "pig_spawn_egg": "Яйцо призыва (pig)",
  "pillager_spawn_egg": "Яйцо призыва (pillager)",
  "pink_banner": "Розовый флаг",
  "pink_bed": "Розовая кровать",
  "pink_bundle": "Розовый мешок",
  "pink_candle": "Розовая свеча",
  "pink_carpet": "Розовый ковёр",
  "pink_concrete": "Розовый бетон",
  "pink_concrete_powder": "Розовый сухой бетон",
  "pink_dye": "Розовый краситель",
  "pink_glazed_terracotta": "Розовая глазурованная керамика",
  "pink_indicator_big": "Pink indicator big",
  "pink_indicator_splash_big": "Pink indicator splash big",
  "pink_shulker_box": "Розовый шалкеровый ящик",
  "pink_stained_glass": "Розовое стекло",
  "pink_stained_glass_pane": "Розовая стеклянная панель",
  "pink_terracotta": "Розовая керамика",
  "pink_tulip": "Pink tulip",
  "pink_wool": "Розовая шерсть",
  "pitcher_plant": "Pitcher plant",
  "pitcher_pod": "Pitcher pod",
  "plenty_pottery_sherd": "Глиняный черепок (plenty)",
  "poison": "Poison",
  "polar_bear_spawn_egg": "Яйцо призыва (polar bear)",
  "polished_andesite_slab": "Polished andesite slab",
  "polished_andesite_stairs": "Polished andesite stairs",
  "polished_blackstone_bricks": "Polished blackstone bricks",
  "polished_blackstone_brick_slab": "Polished blackstone brick slab",
  "polished_blackstone_brick_stairs": "Polished blackstone brick stairs",
  "polished_blackstone_brick_wall": "Polished blackstone brick wall",
  "polished_blackstone_button": "Polished blackstone button",
  "polished_blackstone_pressure_plate": "Polished blackstone pressure plate",
  "polished_blackstone_slab": "Polished blackstone slab",
  "polished_blackstone_stairs": "Polished blackstone stairs",
  "polished_blackstone_wall": "Polished blackstone wall",
  "polished_deepslate_slab": "Polished deepslate slab",
  "polished_deepslate_stairs": "Polished deepslate stairs",
  "polished_deepslate_wall": "Polished deepslate wall",
  "polished_diorite_slab": "Polished diorite slab",
  "polished_diorite_stairs": "Polished diorite stairs",
  "polished_granite_slab": "Polished granite slab",
  "polished_granite_stairs": "Polished granite stairs",
  "polished_tuff": "Polished tuff",
  "polished_tuff_slab": "Polished tuff slab",
  "polished_tuff_stairs": "Polished tuff stairs",
  "polished_tuff_wall": "Polished tuff wall",
  "poppy": "Poppy",
  "prismarine_bricks": "Prismarine bricks",
  "prismarine_brick_slab": "Prismarine brick slab",
  "prismarine_brick_stairs": "Prismarine brick stairs",
  "prismarine_slab": "Prismarine slab",
  "prismarine_stairs": "Prismarine stairs",
  "prismarine_wall": "Prismarine wall",
  "prize_pottery_sherd": "Глиняный черепок (prize)",
  "pufferfish_spawn_egg": "Яйцо призыва (pufferfish)",
  "purple_banner": "Фиолетовый флаг",
  "purple_bed": "Фиолетовая кровать",
  "purple_bundle": "Фиолетовый мешок",
  "purple_candle": "Фиолетовая свеча",
  "purple_carpet": "Фиолетовый ковёр",
  "purple_concrete": "Фиолетовый бетон",
  "purple_concrete_powder": "Фиолетовый сухой бетон",
  "purple_dye": "Фиолетовый краситель",
  "purple_glazed_terracotta": "Фиолетовая глазурованная керамика",
  "purple_stained_glass": "Фиолетовое стекло",
  "purple_stained_glass_pane": "Фиолетовая стеклянная панель",
  "purple_terracotta": "Фиолетовая керамика",
  "purple_wool": "Фиолетовая шерсть",
  "purpur_slab": "Purpur slab",
  "purpur_stairs": "Purpur stairs",
  "quartz_slab": "Quartz slab",
  "quartz_stairs": "Quartz stairs",
  "rabbit_spawn_egg": "Яйцо призыва (rabbit)",
  "rabid": "Rabid",
  "raiser_armor_trim_smithing_template": "Кузнечный шаблон (raiser armor trim)",
  "ravager_spawn_egg": "Яйцо призыва (ravager)",
  "red_banner": "Красный флаг",
  "red_bed": "Красная кровать",
  "red_bundle": "Красный мешок",
  "red_candle": "Красная свеча",
  "red_carpet": "Красный ковёр",
  "red_concrete": "Красный бетон",
  "red_concrete_powder": "Красный сухой бетон",
  "red_dye": "Красный краситель",
  "red_glazed_terracotta": "Красная глазурованная керамика",
  "red_indicator_big": "Red indicator big",
  "red_indicator_splash_big": "Red indicator splash big",
  "red_nether_bricks": "Red nether bricks",
  "red_nether_brick_slab": "Red nether brick slab",
  "red_nether_brick_stairs": "Red nether brick stairs",
  "red_nether_brick_wall": "Red nether brick wall",
  "red_sandstone_slab": "Red sandstone slab",
  "red_sandstone_stairs": "Red sandstone stairs",
  "red_sandstone_wall": "Red sandstone wall",
  "red_shulker_box": "Красный шалкеровый ящик",
  "red_stained_glass": "Красное стекло",
  "red_stained_glass_pane": "Красная стеклянная панель",
  "red_terracotta": "Красная керамика",
  "red_tulip": "Red tulip",
  "red_wool": "Красная шерсть",
  "regeneration": "Regeneration",
  "reinforced_deepslate": "Reinforced deepslate",
  "repeating_command_block": "Repeating command block",
  "resin_block": "Resin block",
  "resin_brick": "Resin brick",
  "resin_bricks": "Resin bricks",
  "resin_brick_slab": "Resin brick slab",
  "resin_brick_stairs": "Resin brick stairs",
  "resin_brick_wall": "Resin brick wall",
  "resin_clump": "Resin clump",
  "resistance": "Resistance",
  "rib_armor_trim_smithing_template": "Кузнечный шаблон (rib armor trim)",
  "root_braiding": "Root braiding",
  "rose_bush": "Rose bush",
  "salmon_spawn_egg": "Яйцо призыва (salmon)",
  "sandstone_slab": "Sandstone slab",
  "sandstone_stairs": "Sandstone stairs",
  "sandstone_wall": "Sandstone wall",
  "saturation": "Saturation",
  "scrape_pottery_sherd": "Глиняный черепок (scrape)",
  "sentry_armor_trim_smithing_template": "Кузнечный шаблон (sentry armor trim)",
  "shaper_armor_trim_smithing_template": "Кузнечный шаблон (shaper armor trim)",
  "sheaf_pottery_sherd": "Глиняный черепок (sheaf)",
  "sheep_spawn_egg": "Яйцо призыва (sheep)",
  "shelter_pottery_sherd": "Глиняный черепок (shelter)",
  "short_grass": "Short grass",
  "shroomlight": "Shroomlight",
  "shulker_spawn_egg": "Яйцо призыва (shulker)",
  "silence_armor_trim_smithing_template": "Кузнечный шаблон (silence armor trim)",
  "silverfish_spawn_egg": "Яйцо призыва (silverfish)",
  "skeleton_horse_spawn_egg": "Яйцо призыва (skeleton horse)",
  "skeleton_skull": "Skeleton skull",
  "skeleton_spawn_egg": "Яйцо призыва (skeleton)",
  "skull_banner_pattern": "Узор флага (skull)",
  "skull_pottery_sherd": "Глиняный черепок (skull)",
  "slime_spawn_egg": "Яйцо призыва (slime)",
  "slowness": "Slowness",
  "slow_falling": "Slow falling",
  "small_amethyst_bud": "Small amethyst bud",
  "small_dripleaf": "Small dripleaf",
  "smooth_quartz_slab": "Smooth quartz slab",
  "smooth_quartz_stairs": "Smooth quartz stairs",
  "smooth_red_sandstone_slab": "Smooth red sandstone slab",
  "smooth_red_sandstone_stairs": "Smooth red sandstone stairs",
  "smooth_sandstone_slab": "Smooth sandstone slab",
  "smooth_sandstone_stairs": "Smooth sandstone stairs",
  "smooth_stone_slab": "Smooth stone slab",
  "sniffer_egg": "Sniffer egg",
  "sniffer_spawn_egg": "Яйцо призыва (sniffer)",
  "snort_pottery_sherd": "Глиняный черепок (snort)",
  "snout_armor_trim_smithing_template": "Кузнечный шаблон (snout armor trim)",
  "snow_golem_spawn_egg": "Яйцо призыва (snow golem)",
  "spawner": "Spawner",
  "speed": "Speed",
  "spider_spawn_egg": "Яйцо призыва (spider)",
  "spire_armor_trim_smithing_template": "Кузнечный шаблон (spire armor trim)",
  "splash_potion": "Splash potion",
  "splash_water_bottle": "Splash water bottle",
  "spruce_boat": "Еловая лодка",
  "spruce_button": "Еловая кнопка",
  "spruce_chest_boat": "Еловая лодка с сундуком",
  "spruce_door": "Еловая дверь",
  "spruce_fence": "Еловый забор",
  "spruce_fence_gate": "Еловая калитка",
  "spruce_hanging_sign": "Еловая подвесная табличка",
  "spruce_leaves": "Листья (еловый)",
  "spruce_log": "Еловое бревно",
  "spruce_planks": "Еловые доски",
  "spruce_pressure_plate": "Еловая нажимная плита",
  "spruce_sapling": "Саженец (еловый)",
  "spruce_sign": "Еловая табличка",
  "spruce_slab": "Еловая плита",
  "spruce_stairs": "Еловые ступеньки",
  "spruce_trapdoor": "Еловый люк",
  "spruce_wood": "Еловая древесина",
  "squid_spawn_egg": "Яйцо призыва (squid)",
  "stone_brick_stairs": "Stone brick stairs",
  "stone_brick_wall": "Stone brick wall",
  "stone_slab": "Stone slab",
  "stone_stairs": "Stone stairs",
  "stray_spawn_egg": "Яйцо призыва (stray)",
  "strength": "Strength",
  "strider_spawn_egg": "Яйцо призыва (strider)",
  "stripped_acacia_log": "Stripped acacia log",
  "stripped_acacia_wood": "Stripped acacia wood",
  "stripped_bamboo_block": "Stripped bamboo block",
  "stripped_birch_log": "Stripped birch log",
  "stripped_birch_wood": "Stripped birch wood",
  "stripped_cherry_log": "Stripped cherry log",
  "stripped_cherry_wood": "Stripped cherry wood",
  "stripped_crimson_hyphae": "Stripped crimson hyphae",
  "stripped_crimson_stem": "Stripped crimson stem",
  "stripped_dark_oak_log": "Stripped dark oak log",
  "stripped_dark_oak_wood": "Stripped dark oak wood",
  "stripped_jungle_log": "Stripped jungle log",
  "stripped_jungle_wood": "Stripped jungle wood",
  "stripped_mangrove_log": "Stripped mangrove log",
  "stripped_mangrove_wood": "Stripped mangrove wood",
  "stripped_pale_oak_log": "Stripped pale oak log",
  "stripped_pale_oak_wood": "Stripped pale oak wood",
  "stripped_spruce_log": "Stripped spruce log",
  "stripped_spruce_wood": "Stripped spruce wood",
  "stripped_warped_hyphae": "Stripped warped hyphae",
  "stripped_warped_stem": "Stripped warped stem",
  "structure_void": "Structure void",
  "suspicious_gravel": "Suspicious gravel",
  "suspicious_sand": "Suspicious sand",
  "tadpole_bucket": "Tadpole bucket",
  "tadpole_spawn_egg": "Яйцо призыва (tadpole)",
  "tall_grass": "Tall grass",
  "terracotta": "Terracotta",
  "tide_armor_trim_smithing_template": "Кузнечный шаблон (tide armor trim)",
  "tinted_glass": "Tinted glass",
  "tipped_arrow": "Tipped arrow",
  "torchflower": "Torchflower",
  "torchflower_seeds": "Torchflower seeds",
  "trader_llama_spawn_egg": "Яйцо призыва (trader llama)",
  "trapped_chest": "Trapped chest",
  "trial_key": "Trial key",
  "trial_spawner": "Trial spawner",
  "tropical_fish_spawn_egg": "Яйцо призыва (tropical fish)",
  "tube_coral": "Tube coral",
  "tube_coral_block": "Tube coral block",
  "tube_coral_fan": "Tube coral fan",
  "tuff_bricks": "Tuff bricks",
  "tuff_brick_slab": "Tuff brick slab",
  "tuff_brick_stairs": "Tuff brick stairs",
  "tuff_brick_wall": "Tuff brick wall",
  "tuff_slab": "Tuff slab",
  "tuff_stairs": "Tuff stairs",
  "tuff_wall": "Tuff wall",
  "turtle_egg": "Turtle egg",
  "turtle_scute": "Turtle scute",
  "turtle_spawn_egg": "Яйцо призыва (turtle)",
  "vex_armor_trim_smithing_template": "Кузнечный шаблон (vex armor trim)",
  "vex_spawn_egg": "Яйцо призыва (vex)",
  "villager_spawn_egg": "Яйцо призыва (villager)",
  "vindicator_spawn_egg": "Яйцо призыва (vindicator)",
  "vulnerability": "Vulnerability",
  "wandering_trader_spawn_egg": "Яйцо призыва (wandering trader)",
  "warden_spawn_egg": "Яйцо призыва (warden)",
  "ward_armor_trim_smithing_template": "Кузнечный шаблон (ward armor trim)",
  "warped_button": "Искажённая кнопка",
  "warped_fence": "Искажённый забор",
  "warped_fence_gate": "Искажённая калитка",
  "warped_hanging_sign": "Искажённая подвесная табличка",
  "warped_pressure_plate": "Искажённая нажимная плита",
  "warped_sign": "Искажённая табличка",
  "warped_wart_block": "Warped wart block",
  "water_bottle": "Water bottle",
  "water_breathing": "Water breathing",
  "waxed_chiseled_copper": "Waxed chiseled copper",
  "waxed_copper_bulb": "Waxed copper bulb",
  "waxed_copper_door": "Waxed copper door",
  "waxed_copper_grate": "Waxed copper grate",
  "waxed_copper_trapdoor": "Waxed copper trapdoor",
  "waxed_cut_copper_slab": "Waxed cut copper slab",
  "waxed_cut_copper_stairs": "Waxed cut copper stairs",
  "waxed_exposed_chiseled_copper": "Waxed exposed chiseled copper",
  "waxed_exposed_copper": "Waxed exposed copper",
  "waxed_exposed_copper_bulb": "Waxed exposed copper bulb",
  "waxed_exposed_copper_door": "Waxed exposed copper door",
  "waxed_exposed_copper_grate": "Waxed exposed copper grate",
  "waxed_exposed_copper_trapdoor": "Waxed exposed copper trapdoor",
  "waxed_exposed_cut_copper": "Waxed exposed cut copper",
  "waxed_exposed_cut_copper_slab": "Waxed exposed cut copper slab",
  "waxed_exposed_cut_copper_stairs": "Waxed exposed cut copper stairs",
  "waxed_oxidized_chiseled_copper": "Waxed oxidized chiseled copper",
  "waxed_oxidized_copper": "Waxed oxidized copper",
  "waxed_oxidized_copper_bulb": "Waxed oxidized copper bulb",
  "waxed_oxidized_copper_door": "Waxed oxidized copper door",
  "waxed_oxidized_copper_grate": "Waxed oxidized copper grate",
  "waxed_oxidized_copper_trapdoor": "Waxed oxidized copper trapdoor",
  "waxed_oxidized_cut_copper": "Waxed oxidized cut copper",
  "waxed_oxidized_cut_copper_slab": "Waxed oxidized cut copper slab",
  "waxed_oxidized_cut_copper_stairs": "Waxed oxidized cut copper stairs",
  "waxed_weathered_chiseled_copper": "Waxed weathered chiseled copper",
  "waxed_weathered_copper": "Waxed weathered copper",
  "waxed_weathered_copper_bulb": "Waxed weathered copper bulb",
  "waxed_weathered_copper_door": "Waxed weathered copper door",
  "waxed_weathered_copper_grate": "Waxed weathered copper grate",
  "waxed_weathered_copper_trapdoor": "Waxed weathered copper trapdoor",
  "waxed_weathered_cut_copper": "Waxed weathered cut copper",
  "waxed_weathered_cut_copper_slab": "Waxed weathered cut copper slab",
  "waxed_weathered_cut_copper_stairs": "Waxed weathered cut copper stairs",
  "wayfinder_armor_trim_smithing_template": "Кузнечный шаблон (wayfinder armor trim)",
  "weakness": "Weakness",
  "weathered_chiseled_copper": "Weathered chiseled copper",
  "weathered_copper_bulb": "Weathered copper bulb",
  "weathered_copper_door": "Weathered copper door",
  "weathered_copper_grate": "Weathered copper grate",
  "weathered_copper_trapdoor": "Weathered copper trapdoor",
  "weathered_cut_copper": "Weathered cut copper",
  "weathered_cut_copper_slab": "Weathered cut copper slab",
  "weathered_cut_copper_stairs": "Weathered cut copper stairs",
  "white_bundle": "Белый мешок",
  "white_concrete_powder": "Белый сухой бетон",
  "white_glazed_terracotta": "Белая глазурованная керамика",
  "white_shulker_box": "Белый шалкеровый ящик",
  "white_stained_glass_pane": "Белая стеклянная панель",
  "white_terracotta": "Белая керамика",
  "white_tulip": "White tulip",
  "wild_armor_trim_smithing_template": "Кузнечный шаблон (wild armor trim)",
  "witch_spawn_egg": "Яйцо призыва (witch)",
  "wither_effect": "Wither effect",
  "wither_skeleton_spawn_egg": "Яйцо призыва (wither skeleton)",
  "wither_spawn_egg": "Яйцо призыва (wither)",
  "wolf_armor": "Wolf armor",
  "wolf_spawn_egg": "Яйцо призыва (wolf)",
  "writable_book": "Writable book",
  "yellow_bundle": "Жёлтый мешок",
  "yellow_concrete_powder": "Жёлтый сухой бетон",
  "yellow_glazed_terracotta": "Жёлтая глазурованная керамика",
  "yellow_indicator_big": "Yellow indicator big",
  "yellow_indicator_splash_big": "Yellow indicator splash big",
  "yellow_shulker_box": "Жёлтый шалкеровый ящик",
  "yellow_stained_glass_pane": "Жёлтая стеклянная панель",
  "yellow_terracotta": "Жёлтая керамика",
  "zoglin_spawn_egg": "Яйцо призыва (zoglin)",
  "zombie_head": "Zombie head",
  "zombie_horse_spawn_egg": "Яйцо призыва (zombie horse)",
  "zombie_spawn_egg": "Яйцо призыва (zombie)",
  "zombie_villager_spawn_egg": "Яйцо призыва (zombie villager)",
  "zombified_piglin_spawn_egg": "Яйцо призыва (zombified piglin)"
};

export const getItemTitle = (itemName: string): string => {
  if (!itemName) return ''
  const cleanName = itemName.trim().toLowerCase()
  if (ruItemNames[cleanName]) {
    return ruItemNames[cleanName]
  }
  return itemName.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')
}

export const getItemWikiUrl = (itemName: string): string => {
  if (!itemName) return ''
  const title = getItemTitle(itemName)
  return `https://ru.minecraft.wiki/w/${encodeURIComponent(title.replace(/ /g, '_'))}`
}

export const getItemAlt = (itemName: string): string => {
  if (!itemName) return ''
  const title = getItemTitle(itemName)
  return `Иконка ${title}.png: Спрайт для инвентаря, как показано в игре.`
}

export const getItemSrc = (itemName: string): string => {
  if (!itemName) return ''
  if (itemName.startsWith('/') || itemName.includes('.')) {
    return itemName
  }
  return `/assets/items/${itemName}.png`
}
